
-- Run this SQL in your Supabase SQL Editor to add the 20 newly bulk imported products to your live database!

INSERT INTO products (name, slug, description, collection_name, collection_slug, relationships, celebrations, tag, image_url, images, stock, item_count, is_visible, sort_order)
VALUES
(
    'Chips & Chocolate Hamper', 
    'chips-chocolate-hamper', 
    'A delightful hamper filled with premium chips and chocolates.', 
    'Hamper', 
    'hamper', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/chips-chocolate-hamper-1.jpg', 
    ARRAY['/images/products/chips-chocolate-hamper-1.jpg', '/images/products/chips-chocolate-hamper-2.jpg'], 
    10, 
    24, 
    true, 
    50
  ),
(
    'Big Mix Hamper', 
    'big-mix-hamper', 
    'An oversized mix hamper perfect for huge celebrations.', 
    'Hamper', 
    'hamper', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/big-mix-hamper-1.jpg', 
    ARRAY['/images/products/big-mix-hamper-1.jpg', '/images/products/big-mix-hamper-2.jpg'], 
    10, 
    19, 
    true, 
    51
  ),
(
    'Scented Candle Gift', 
    'scented-candle-gift', 
    'A single, perfectly made scented candle for creating a warm mood.', 
    'Personalized', 
    'personalized', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/scented-candle-gift-1.jpg', 
    ARRAY['/images/products/scented-candle-gift-1.jpg', '/images/products/scented-candle-gift-2.jpg'], 
    10, 
    9, 
    true, 
    52
  ),
(
    'Celebrations Gift Box', 
    'celebrations-gift-box', 
    'A beautiful gift box filled with celebrations chocolates and joy.', 
    'Chocolate Bouquet', 
    'chocolate-bouquet', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/celebrations-gift-box-1.jpg', 
    ARRAY['/images/products/celebrations-gift-box-1.jpg', '/images/products/celebrations-gift-box-2.jpg', '/images/products/celebrations-gift-box-3.jpg'], 
    10, 
    9, 
    true, 
    53
  ),
(
    'Premium Chocolate Gift Set', 
    'premium-chocolate-gift-set', 
    'A luxurious chocolate gift arrangement.', 
    'Chocolate Bouquet', 
    'chocolate-bouquet', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/premium-chocolate-gift-set-1.jpg', 
    ARRAY['/images/products/premium-chocolate-gift-set-1.jpg', '/images/products/premium-chocolate-gift-set-2.jpg', '/images/products/premium-chocolate-gift-set-3.jpg'], 
    10, 
    14, 
    true, 
    54
  ),
(
    'Gourmet Chocolate Hamper', 
    'gourmet-chocolate-hamper', 
    'A beautiful hamper basket with carefully arranged gourmet chocolates.', 
    'Hamper', 
    'hamper', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/gourmet-chocolate-hamper-1.jpg', 
    ARRAY['/images/products/gourmet-chocolate-hamper-1.jpg', '/images/products/gourmet-chocolate-hamper-2.jpg'], 
    10, 
    6, 
    true, 
    55
  ),
(
    'Printed Coffee Mug Bundle', 
    'printed-coffee-mug-bundle', 
    'A wonderful coffee mug bundle to start the day right.', 
    'Personalized', 
    'personalized', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/printed-coffee-mug-bundle-1.jpg', 
    ARRAY['/images/products/printed-coffee-mug-bundle-1.jpg', '/images/products/printed-coffee-mug-bundle-2.jpg', '/images/products/printed-coffee-mug-bundle-3.jpg', '/images/products/printed-coffee-mug-bundle-4.jpg'], 
    10, 
    21, 
    true, 
    56
  ),
(
    'Dairy Milk Silk Bouquet', 
    'dairy-milk-silk-bouquet', 
    'A delicious arrangement of Dairy Milk Silk chocolates wrapped beautifully.', 
    'Chocolate Bouquet', 
    'chocolate-bouquet', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/dairy-milk-silk-bouquet-1.jpg', 
    ARRAY['/images/products/dairy-milk-silk-bouquet-1.jpg', '/images/products/dairy-milk-silk-bouquet-2.jpg'], 
    10, 
    15, 
    true, 
    57
  ),
(
    'Ferrero Rocher Bouquet', 
    'ferrero-rocher-bouquet', 
    'Golden Ferrero Rocher chocolates presented in a wonderful bouquet style.', 
    'Chocolate Bouquet', 
    'chocolate-bouquet', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/ferrero-rocher-bouquet-1.jpg', 
    ARRAY['/images/products/ferrero-rocher-bouquet-1.jpg', '/images/products/ferrero-rocher-bouquet-2.jpg'], 
    10, 
    6, 
    true, 
    58
  ),
(
    'Friends Forever Rose Bouquet', 
    'friends-forever-rose-bouquet', 
    'A meaningful rose bouquet to celebrate everlasting friendship.', 
    'Fresh Flower', 
    'fresh-flower', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/friends-forever-rose-bouquet-1.jpg', 
    ARRAY['/images/products/friends-forever-rose-bouquet-1.jpg', '/images/products/friends-forever-rose-bouquet-2.jpg'], 
    10, 
    10, 
    true, 
    59
  ),
(
    'Happy Birthday Rose Bouquet', 
    'happy-birthday-rose-bouquet', 
    'A vibrant rose bouquet perfectly crafted for birthday gifting.', 
    'Fresh Flower', 
    'fresh-flower', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/happy-birthday-rose-bouquet-1.jpg', 
    ARRAY['/images/products/happy-birthday-rose-bouquet-1.jpg', '/images/products/happy-birthday-rose-bouquet-2.jpg'], 
    10, 
    7, 
    true, 
    60
  ),
(
    'Kinder Joy Surprise Bouquet', 
    'kinder-joy-surprise-bouquet', 
    'A fun bouquet packed with Kinder Joy eggs, perfect for kids or the young at heart.', 
    'Teddy and Bouquet', 
    'teddy-and-bouquet', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/kinder-joy-surprise-bouquet-1.jpg', 
    ARRAY['/images/products/kinder-joy-surprise-bouquet-1.jpg', '/images/products/kinder-joy-surprise-bouquet-2.jpg'], 
    10, 
    23, 
    true, 
    61
  ),
(
    'White Lily Elegance Bouquet', 
    'white-lily-elegance-bouquet', 
    'A wonderfully elegant bouquet of pure white lilies.', 
    'Fresh Flower', 
    'fresh-flower', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/white-lily-elegance-bouquet-1.jpg', 
    ARRAY['/images/products/white-lily-elegance-bouquet-1.jpg', '/images/products/white-lily-elegance-bouquet-2.jpg', '/images/products/white-lily-elegance-bouquet-3.jpg', '/images/products/white-lily-elegance-bouquet-4.jpg'], 
    10, 
    12, 
    true, 
    62
  ),
(
    'Mix Chocolate Bouquet', 
    'mix-chocolate-bouquet', 
    'A mix of various beloved chocolates curated into an impressive bouquet.', 
    'Chocolate Bouquet', 
    'chocolate-bouquet', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/mix-chocolate-bouquet-1.jpg', 
    ARRAY['/images/products/mix-chocolate-bouquet-1.jpg', '/images/products/mix-chocolate-bouquet-2.jpg', '/images/products/mix-chocolate-bouquet-3.jpg', '/images/products/mix-chocolate-bouquet-4.jpg', '/images/products/mix-chocolate-bouquet-5.jpg'], 
    10, 
    6, 
    true, 
    63
  ),
(
    'Orchid Dream Bouquet', 
    'orchid-dream-bouquet', 
    'Striking, exotic orchids arranged elegantly in a bouquet.', 
    'Fresh Flower', 
    'fresh-flower', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/orchid-dream-bouquet-1.jpg', 
    ARRAY['/images/products/orchid-dream-bouquet-1.jpg', '/images/products/orchid-dream-bouquet-2.jpg'], 
    10, 
    22, 
    true, 
    64
  ),
(
    'Plant & Chocolate Hamper', 
    'plant-chocolate-hamper', 
    'The perfect combination of a serene live plant and delicious chocolates.', 
    'Hamper', 
    'hamper', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/plant-chocolate-hamper-1.jpg', 
    ARRAY['/images/products/plant-chocolate-hamper-1.jpg'], 
    10, 
    11, 
    true, 
    65
  ),
(
    'Classic Red Rose Mix', 
    'classic-red-rose-mix', 
    'Dazzling classic red roses bundled perfectly into a beautiful bouquet.', 
    'Fresh Flower', 
    'fresh-flower', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/classic-red-rose-mix-1.jpg', 
    ARRAY['/images/products/classic-red-rose-mix-1.jpg', '/images/products/classic-red-rose-mix-2.jpg', '/images/products/classic-red-rose-mix-3.jpg', '/images/products/classic-red-rose-mix-4.jpg', '/images/products/classic-red-rose-mix-5.jpg'], 
    10, 
    22, 
    true, 
    66
  ),
(
    'Teddy & Chocolate Mix Hamper', 
    'teddy-chocolate-mix-hamper', 
    'A cuddly teddy bear together with assorted chocolates gracefully packed in a hamper.', 
    'Teddy and Bouquet', 
    'teddy-and-bouquet', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/teddy-chocolate-mix-hamper-1.jpg', 
    ARRAY['/images/products/teddy-chocolate-mix-hamper-1.jpg', '/images/products/teddy-chocolate-mix-hamper-2.jpg'], 
    10, 
    17, 
    true, 
    67
  ),
(
    'Sunshine Yellow Rose Bouquet', 
    'sunshine-yellow-rose-bouquet', 
    'Bright and cheerful yellow roses to instantly lift someone''s spirits.', 
    'Fresh Flower', 
    'fresh-flower', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/sunshine-yellow-rose-bouquet-1.jpg', 
    ARRAY['/images/products/sunshine-yellow-rose-bouquet-1.jpg', '/images/products/sunshine-yellow-rose-bouquet-2.jpg', '/images/products/sunshine-yellow-rose-bouquet-3.jpg'], 
    10, 
    7, 
    true, 
    68
  ),
(
    'Classic Gift Hamper Set', 
    'classic-gift-hamper-set', 
    'A beautiful collection of classic gifts arranged for any fine occasion.', 
    'Hamper', 
    'hamper', 
    ARRAY['Friend', 'Family', 'Girlfriend'], 
    ARRAY['Birthday', 'Anniversary'], 
    'New Arrival', 
    '/images/products/classic-gift-hamper-set-1.jpg', 
    ARRAY['/images/products/classic-gift-hamper-set-1.jpg', '/images/products/classic-gift-hamper-set-2.jpg', '/images/products/classic-gift-hamper-set-3.jpg', '/images/products/classic-gift-hamper-set-4.jpg'], 
    10, 
    18, 
    true, 
    69
  )
ON CONFLICT (slug) DO UPDATE 
SET 
  description = EXCLUDED.description,
  collection_name = EXCLUDED.collection_name,
  collection_slug = EXCLUDED.collection_slug,
  tag = EXCLUDED.tag,
  image_url = EXCLUDED.image_url,
  images = EXCLUDED.images,
  item_count = EXCLUDED.item_count;
