export interface Product {
    id: string;
    name: string;
    slug: string;
    description: string;
    collection: string;
    collectionSlug: string;
    relationships: string[];
    celebrations: string[];
    tag: 'Best Seller' | 'New Arrival' | 'Seasonal' | 'Standard';
    image_url: string;
    images: string[];
    imageScale?: number;
    stock: number;
    itemCount?: number;
}

export const PRODUCTS: Product[] = [
    // ── ROSES ──
    {
        id: '1',
        name: 'Crimson Elegance Bouquet',
        slug: 'crimson-elegance-bouquet',
        description: 'Deep red premium roses wrapped in elegant eco-style packaging. A timeless expression of love and passion, handpicked at dawn for peak freshness and arranged by our master florists.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Girlfriend', 'Wife'],
        celebrations: ['Anniversary', "Women's Day"],
        tag: 'Best Seller',
        image_url: '/images/products/crimson-elegance-bouquet.webp',
        images: ['/images/products/crimson-elegance-bouquet.webp'],
        stock: 10,
        itemCount: 24,
    },
    {
        id: '2',
        name: 'Blush Harmony Roses',
        slug: 'blush-harmony-roses',
        description: 'Soft blush pink roses arranged in a graceful hand-tied style. Delicate and romantic, these roses are perfect for celebrating the special women in your life.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Her', 'Wife'],
        celebrations: ["Women's Day"],
        tag: 'Standard',
        image_url: '/images/products/blush-harmony-roses.webp',
        images: ['/images/products/blush-harmony-roses.webp'],
        stock: 10,
        itemCount: 15,
    },
    {
        id: '3',
        name: 'Ivory Serenity Bloom',
        slug: 'ivory-serenity-bloom',
        description: 'Elegant white roses symbolizing purity and peace. A refined choice for friends and corporate gifting, beautifully wrapped in premium eco-packaging.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend', 'Corporate'],
        celebrations: ['Eid'],
        tag: 'Standard',
        image_url: '/images/products/ivory-serenity-bloom.webp',
        images: ['/images/products/ivory-serenity-bloom.webp'],
        stock: 10,
        itemCount: 20,
    },
    {
        id: '4',
        name: 'Heart Shape Rose Box',
        slug: 'heart-shape-rose-box',
        description: 'Romantic heart-shaped box filled with fresh red roses. A stunning declaration of love, crafted to make anniversaries and special moments truly unforgettable.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Girlfriend', 'Wife'],
        celebrations: ['Anniversary'],
        tag: 'Best Seller',
        image_url: '/images/products/heart-shape-rose-box.webp',
        images: ['/images/products/heart-shape-rose-box.webp'],
        stock: 10,
        itemCount: 30,
    },

    // ── LUXURY BOUQUETS ──
    {
        id: '5',
        name: 'Royal Crimson Symphony',
        slug: 'royal-crimson-symphony',
        description: 'A grand bouquet of red and blush roses with luxury fillers. This opulent arrangement is crafted for those who believe love deserves the grandest expression.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Wife', 'Girlfriend'],
        celebrations: ['Anniversary'],
        tag: 'Best Seller',
        image_url: '/images/products/royal-crimson-symphony.webp',
        images: ['/images/products/royal-crimson-symphony.webp'],
        stock: 10,
        itemCount: 50,
    },
    {
        id: '6',
        name: 'Champagne Bloom Delight',
        slug: 'champagne-bloom-delight',
        description: 'Soft champagne roses in premium wrapping. A sophisticated and modern arrangement that celebrates femininity with understated luxury.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Her'],
        celebrations: ["Women's Day"],
        tag: 'New Arrival',
        image_url: '/images/products/champagne-bloom-delight.webp',
        images: ['/images/products/champagne-bloom-delight.webp'],
        imageScale: 1.25,
        stock: 10,
        itemCount: 18,
    },
    {
        id: '7',
        name: 'Emerald Luxe Arrangement',
        slug: 'emerald-luxe-arrangement',
        description: 'A refined green-toned luxury floral composition. Sophisticated and bold, this arrangement is designed for the modern gentleman who appreciates the finer things.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Him', 'Husband'],
        celebrations: ['Corporate Events'],
        tag: 'Standard',
        image_url: '/images/products/emerald-luxe-arrangement.webp',
        images: ['/images/products/emerald-luxe-arrangement.webp'],
        stock: 10,
        itemCount: 12,
    },
    {
        id: '8',
        name: 'Prestige Floral Ensemble',
        slug: 'prestige-floral-ensemble',
        description: 'Sophisticated floral mix crafted for celebrations. A vibrant and joyful arrangement that brings the spirit of festivity to every occasion.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend'],
        celebrations: ['Holi'],
        tag: 'Standard',
        image_url: '/images/products/prestige-floral-ensemble.webp',
        images: ['/images/products/prestige-floral-ensemble.webp'],
        stock: 10,
        itemCount: 20,
    },

    // ── PERSONALIZED GIFTS ──
    {
        id: '9',
        name: 'Custom Name Rose Box',
        slug: 'custom-name-rose-box',
        description: 'Personalized rose box engraved with a custom name. A deeply personal and romantic gift that transforms a beautiful bouquet into a lasting keepsake.',
        collection: 'Personalized',
        collectionSlug: 'personalized',
        relationships: ['Girlfriend', 'Wife'],
        celebrations: ['Anniversary'],
        tag: 'Best Seller',
        image_url: '/images/products/custom-name-rose-box.webp',
        images: ['/images/products/custom-name-rose-box.webp'],
        stock: 10,
    },
    {
        id: '10',
        name: 'Photo Memory Gift Set',
        slug: 'photo-memory-gift-set',
        description: 'Floral gift combo paired with a custom photo frame. Celebrate your most cherished memories with a gift that combines the beauty of fresh flowers with a personalized keepsake.',
        collection: 'Personalized',
        collectionSlug: 'personalized',
        relationships: ['Husband', 'Wife'],
        celebrations: ['Anniversary'],
        tag: 'Standard',
        image_url: '/images/products/photo-memory-gift-set.webp',
        images: ['/images/products/photo-memory-gift-set.webp'],
        stock: 10,
    },
    {
        id: '11',
        name: 'Personalized Mug & Roses',
        slug: 'personalized-mug-and-roses',
        description: 'Custom printed mug paired with fresh roses. A charming and thoughtful gift that combines everyday warmth with the beauty of fresh blooms.',
        collection: 'Personalized',
        collectionSlug: 'personalized',
        relationships: ['Boyfriend', 'Girlfriend'],
        celebrations: ['Birthday'],
        tag: 'New Arrival',
        image_url: '/images/products/personalized-mug-and-roses.webp',
        images: ['/images/products/personalized-mug-and-roses.webp'],
        stock: 10,
        itemCount: 8,
    },
    {
        id: '12',
        name: 'Engraved Wooden Keepsake',
        slug: 'engraved-wooden-keepsake',
        description: 'Elegant engraved wooden gift with floral accent. A timeless and sophisticated keepsake that honors the special bond between husband and wife.',
        collection: 'Personalized',
        collectionSlug: 'personalized',
        relationships: ['Husband'],
        celebrations: ['Husband Appreciation Day'],
        tag: 'Standard',
        image_url: '/images/products/engraved-wooden-keepsake.webp',
        images: ['/images/products/engraved-wooden-keepsake.webp'],
        stock: 10,
    },

    // ── ANNIVERSARY COLLECTION ──
    {
        id: '13',
        name: 'Golden Anniversary Bloom',
        slug: 'golden-anniversary-bloom',
        description: 'Elegant floral bouquet crafted for milestone anniversaries. A golden tribute to enduring love, featuring premium blooms arranged with timeless grace.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Wife'],
        celebrations: ['Anniversary'],
        tag: 'Best Seller',
        image_url: '/images/products/golden-anniversary-bloom.webp',
        images: ['/images/products/golden-anniversary-bloom.webp'],
        stock: 10,
        itemCount: 25,
    },
    {
        id: '14',
        name: 'Forever Together Bouquet',
        slug: 'forever-together-bouquet',
        description: 'Romantic floral arrangement celebrating eternal love. A beautifully curated bouquet that speaks the language of forever, perfect for couples celebrating their journey.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Couple'],
        celebrations: ['Anniversary'],
        tag: 'Standard',
        image_url: '/images/products/forever-together-bouquet.webp',
        images: ['/images/products/forever-together-bouquet.webp'],
        stock: 10,
        itemCount: 40,
    },
    {
        id: '15',
        name: 'Ruby Romance Collection',
        slug: 'ruby-romance-collection',
        description: 'Deep red roses designed for romantic occasions. A passionate and bold collection that captures the intensity of love, perfect for anniversaries and romantic gestures.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Girlfriend'],
        celebrations: ['Anniversary'],
        tag: 'Standard',
        image_url: '/images/products/ruby-romance-collection.webp',
        images: ['/images/products/ruby-romance-collection.webp'],
        stock: 10,
        itemCount: 36,
    },

    // ── CORPORATE GIFTING ──
    {
        id: '16',
        name: 'Executive Floral Hamper',
        slug: 'executive-floral-hamper',
        description: 'Premium executive hamper for business gifting. A sophisticated and thoughtfully curated hamper that makes a powerful statement in professional relationships.',
        collection: 'Hamper',
        collectionSlug: 'hamper',
        relationships: ['Him'],
        celebrations: ['Corporate Events'],
        tag: 'Best Seller',
        image_url: '/images/products/executive-floral-hamper.webp',
        images: ['/images/products/executive-floral-hamper.webp'],
        stock: 10,
    },
    {
        id: '17',
        name: 'Corporate Appreciation Box',
        slug: 'corporate-appreciation-box',
        description: 'Luxury thank-you gift for valued clients. An elegant and premium gift box that expresses gratitude and strengthens professional bonds with style.',
        collection: 'Hamper',
        collectionSlug: 'hamper',
        relationships: ['Corporate'],
        celebrations: ['Festive Events'],
        tag: 'Standard',
        image_url: '/images/products/corporate-appreciation-box.webp',
        images: ['/images/products/corporate-appreciation-box.webp'],
        stock: 10,
    },
    {
        id: '18',
        name: 'Signature Business Bloom',
        slug: 'signature-business-bloom',
        description: 'Minimalist professional floral arrangement. Clean, refined, and impactful — a floral statement that speaks volumes in any professional setting.',
        collection: 'Hamper',
        collectionSlug: 'hamper',
        relationships: ['Him'],
        celebrations: ['Office Celebrations'],
        tag: 'New Arrival',
        image_url: '/images/products/signature-business-bloom.webp',
        images: ['/images/products/signature-business-bloom.webp'],
        stock: 10,
    },

    // ── SEASONAL ──
    {
        id: '19',
        name: 'Holi Color Splash Bouquet',
        slug: 'holi-color-splash-bouquet',
        description: 'Vibrant bouquet inspired by Holi colors. A joyful and exuberant arrangement bursting with color, celebrating the festival of love and friendship.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend'],
        celebrations: ['Holi'],
        tag: 'Seasonal',
        image_url: '/images/products/holi-color-splash-bouquet.webp',
        images: ['/images/products/holi-color-splash-bouquet.webp'],
        stock: 10,
        itemCount: 22,
    },
    {
        id: '20',
        name: 'Eid Mubarak Luxe Hamper',
        slug: 'eid-mubarak-luxe-hamper',
        description: 'Elegant festive hamper with premium floral touch. A beautifully curated Eid gift that combines luxury and warmth, perfect for family and corporate gifting.',
        collection: 'Hamper',
        collectionSlug: 'hamper',
        relationships: ['Family', 'Corporate'],
        celebrations: ['Eid'],
        tag: 'Seasonal',
        image_url: '/images/products/eid-mubarak-luxe-hamper.webp',
        images: ['/images/products/eid-mubarak-luxe-hamper.webp'],
        stock: 10,
    },
    {
        id: '21',
        name: 'Divine Navratri Bloom Box',
        slug: 'divine-navratri-bloom-box',
        description: 'Festive floral arrangement inspired by Navratri. A divine and colorful bloom box that captures the spiritual energy and vibrant spirit of the festival.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Family'],
        celebrations: ['Navratri'],
        tag: 'Seasonal',
        image_url: '/images/products/divine-navratri-bloom-box.webp',
        images: ['/images/products/divine-navratri-bloom-box.webp'],
        stock: 10,
        itemCount: 16,
    },
    {
        id: '22',
        name: "Gentleman's Luxury Gift Set",
        slug: 'gentlemans-luxury-gift-set',
        description: 'Premium curated gift box for modern gentlemen. A sophisticated and thoughtfully assembled gift set that celebrates the special men in your life with unmatched elegance.',
        collection: 'Personalized',
        collectionSlug: 'personalized',
        relationships: ['Husband', 'Boyfriend'],
        celebrations: ['Husband Appreciation Day'],
        tag: 'New Arrival',
        image_url: '/images/products/gentlemans-luxury-gift-set.webp',
        images: ['/images/products/gentlemans-luxury-gift-set.webp'],
        stock: 10,
    },

    // ── NEW PRODUCTS ──
    {
        id: '23',
        name: 'Mix Flowers',
        slug: 'mix-flowers',
        description: 'Beautiful mix flowers arrangement crafted with fresh blooms.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend', 'Family'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'New Arrival',
        image_url: '/images/products/mix-flowers.webp',
        images: ['/images/products/mix-flowers.webp'],
        stock: 10,
        itemCount: 15,
    },
    {
        id: '24',
        name: 'Roses',
        slug: 'roses-new',
        description: 'Beautiful roses arrangement crafted with fresh blooms.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend', 'Family'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'New Arrival',
        image_url: '/images/products/roses.webp',
        images: ['/images/products/roses.webp'],
        stock: 10,
        itemCount: 12,
    },
    {
        id: '25',
        name: 'Carnation',
        slug: 'carnation',
        description: 'Beautiful carnation arrangement crafted with fresh blooms.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend', 'Family'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'New Arrival',
        image_url: '/images/products/carnation.webp',
        images: ['/images/products/carnation.webp'],
        stock: 10,
        itemCount: 10,
    },
    {
        id: '26',
        name: 'Lily',
        slug: 'lily',
        description: 'Beautiful lily arrangement crafted with fresh blooms.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend', 'Family'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'New Arrival',
        image_url: '/images/products/lily.webp',
        images: ['/images/products/lily.webp'],
        stock: 10,
        itemCount: 5,
    },
    {
        id: '27',
        name: 'Daisy',
        slug: 'daisy',
        description: 'Beautiful daisy arrangement crafted with fresh blooms.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend', 'Family'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'New Arrival',
        image_url: '/images/products/daisy.webp',
        images: ['/images/products/daisy.webp'],
        stock: 10,
        itemCount: 20,
    },
    {
        id: '28',
        name: 'Orchids',
        slug: 'orchids',
        description: 'Beautiful orchids arrangement crafted with fresh blooms.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend', 'Family'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'New Arrival',
        image_url: '/images/products/orchids.webp',
        images: ['/images/products/orchids.webp'],
        stock: 10,
        itemCount: 10,
    },
    {
        id: '29',
        name: 'Gerbera',
        slug: 'gerbera',
        description: 'Beautiful gerbera arrangement crafted with fresh blooms.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend', 'Family'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'New Arrival',
        image_url: '/images/products/gerbera.webp',
        images: ['/images/products/gerbera.webp'],
        stock: 10,
        itemCount: 12,
    },
    {
        id: '30',
        name: 'Sunflower',
        slug: 'sunflower',
        description: 'Beautiful sunflower arrangement crafted with fresh blooms.',
        collection: 'Fresh Flower',
        collectionSlug: 'fresh-flower',
        relationships: ['Friend', 'Family'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'New Arrival',
        image_url: '/images/products/sunflower.webp',
        images: ['/images/products/sunflower.webp'],
        stock: 10,
        itemCount: 5,
    },
    // ── PLANTS ──
    {
        id: '31',
        name: 'Lucky Bamboo',
        slug: 'lucky-bamboo',
        description: 'A beautiful indoor Lucky Bamboo plant symbolizing good luck and prosperity. Perfect for gifting and home decor.',
        collection: 'Plants',
        collectionSlug: 'plants',
        relationships: ['Friend', 'Family', 'Corporate'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'Best Seller',
        image_url: '/images/products/lucky-bamboo-1.webp',
        images: [
            '/images/products/lucky-bamboo-1.webp',
            '/images/products/lucky-bamboo-2.webp',
            '/images/products/lucky-bamboo-3.webp'
        ],
        stock: 10,
        itemCount: 3, // Number of stalks
    },
    {
        id: '32',
        name: 'Jade Plant',
        slug: 'jade-plant',
        description: 'A stunning Jade Plant known for attracting wealth and financial success. Easy to care for and highly decorative.',
        collection: 'Plants',
        collectionSlug: 'plants',
        relationships: ['Friend', 'Family', 'Corporate'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'New Arrival',
        image_url: '/images/products/jade-plant-1.webp',
        images: [
            '/images/products/jade-plant-1.webp',
            '/images/products/jade-plant-2.webp',
            '/images/products/jade-plant-3.webp'
        ],
        stock: 10,
        itemCount: 1,
    },
    {
        id: '33',
        name: 'ZZ Plant',
        slug: 'zz-plant',
        description: 'The highly resilient ZZ plant with its glossy, dark green leaves. Perfect for modern spaces and requires very little maintenance.',
        collection: 'Plants',
        collectionSlug: 'plants',
        relationships: ['Friend', 'Family', 'Corporate'],
        celebrations: ['Birthday', 'Anniversary'],
        tag: 'Standard',
        image_url: '/images/products/zz-plant-1.webp',
        images: [
            '/images/products/zz-plant-1.webp',
            '/images/products/zz-plant-2.webp',
            '/images/products/zz-plant-3.webp',
            '/images/products/zz-plant-4.webp'
        ],
        stock: 10,
        itemCount: 1,
    },
];

// Helper functions
export function getProductBySlug(slug: string): Product | undefined {
    return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCollection(collectionSlug: string): Product[] {
    return PRODUCTS.filter((p) => p.collectionSlug === collectionSlug);
}

export function getProductsByTag(tag: Product['tag']): Product[] {
    return PRODUCTS.filter((p) => p.tag === tag);
}

export function getProductsByRelationship(relationship: string): Product[] {
    return PRODUCTS.filter((p) =>
        p.relationships.some((r) => r.toLowerCase() === relationship.toLowerCase())
    );
}

export function getProductsByCelebration(celebration: string): Product[] {
    return PRODUCTS.filter((p) =>
        p.celebrations.some((c) => c.toLowerCase() === celebration.toLowerCase())
    );
}

export const COLLECTIONS = [
    { name: 'Fresh Flower', slug: 'fresh-flower' },
    { name: 'Chocolate Bouquet', slug: 'chocolate-bouquet' },
    { name: 'Teddy and Bouquet', slug: 'teddy-and-bouquet' },
    { name: 'Personalized', slug: 'personalized' },
    { name: 'Hamper', slug: 'hamper' },
    { name: 'Plants', slug: 'plants' },
    { name: 'Cake', slug: 'cake' },
    { name: 'Balloon Bouquet', slug: 'balloon-bouquet' },
];
